/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fire.alarm.desktopi.client;

import firealarm.rmi.api.FireAlarmSensor;

/**
 *
 * @author nuwan
 */
public class SensorItem extends javax.swing.JPanel {

    /**
     * Creates new form SensorItem
     */
    public SensorItem() {
        initComponents();
    }

    public void setSensor(FireAlarmSensor sensor){
        sensorLocation.setText(sensor.getFloor() + " " + sensor.getRoom());
        co2Level.setValue(sensor.getCo2Level() * 10);
        smokeLevel.setValue(sensor.getSmokeLevel() * 10);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        sensorLocation = new javax.swing.JLabel();
        smokeLevel = new javax.swing.JProgressBar();
        co2Level = new javax.swing.JProgressBar();

        setAlignmentX(0.5F);
        setPreferredSize(new java.awt.Dimension(150, 200));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fire/alarm/desktopi/client/assets/Emergency bell.png"))); // NOI18N
        jLabel1.setAlignmentX(0.5F);
        jLabel1.setPreferredSize(new java.awt.Dimension(50, 50));
        jLabel1.setVerifyInputWhenFocusTarget(false);
        add(jLabel1);

        sensorLocation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sensorLocation.setText("jLabel1");
        sensorLocation.setAlignmentX(0.5F);
        add(sensorLocation);
        add(smokeLevel);
        add(co2Level);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar co2Level;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel sensorLocation;
    private javax.swing.JProgressBar smokeLevel;
    // End of variables declaration//GEN-END:variables
}
